services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"] # Start the server in development mode
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - keycloak

  frontend:
    build: ./frontend
    ports:
      - "8082:80"
    depends_on:
      - backend

